apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: timestamp
          emptyDir: {}
        #- name: log-output-pingpong
        #  persistentVolumeClaim:
        #    claimName: log-output-pingpong-claim
      containers:
        - name: log-output-writer
          image: keskimaki/log-output-writer:0.1
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: keskimaki/log-output-reader:1.2
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
          #  - name: log-output-pingpong
          #    mountPath: /usr/src/app/pingpong
