apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: timestamp
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: keskimaki/log-output-writer:0.1
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: keskimaki/log-output-reader:0.1
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
