apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: log-output-pingpong
  name: log-output-pingpong-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
