apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: log-output-pingpong
          persistentVolumeClaim:
            claimName: log-output-pingpong-claim
      containers:
        - name: pingpong
          image: keskimaki/pingpong:0.6
          volumeMounts:
            - name: log-output-pingpong
              mountPath: /usr/src/app/pingpong
