apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: kube-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      labels:
        app: kube-project
    spec:
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: kube-project-claim
      containers:
        - name: kube-project
          image: keskimaki/kube-project-front:0.6
        - name: kube-project-api
          image: keskimaki/kube-project-api:1.2
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: files
              #valueFrom:
              #  configMapKeyRef:
              #    name: dotenv-configmap
              #    key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: dotenv-configmap
